##################################################################
### SPRING
##################################################################
spring:
    #应用唯一标识
    application:
        name: ALICE-CODE-CREATOR
    profiles:
        active: dev
    mvc:
        static-path-pattern: /**
        servlet:
            load-on-startup: 1
    resources:
        # 是否开启默认的资源处理
        add-mappings: true
    freemarker:
        template-loader-path: classpath:/templates/
        prefix:
        suffix: .ftl
        charset: UTF-8
        content-type: text/html
        cache: false
        request-context-attribute: request
        check-template-location: true
        allow-request-override: false
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        joda-date-time-format: yyyy-MM-dd HH:mm:ss
        default-property-inclusion: non_null #JSON不给前台返回空值